package museumexhibition.ui.form.exhibition;

import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import museumexhibition.domain.*;
import museumexhibition.service.ExhibitService;
import museumexhibition.service.ExhibitionService;
import museumexhibition.service.MuseumService;
import museumexhibition.service.impl.ExhibitServiceImpl;
import museumexhibition.service.impl.ExhibitionServiceImpl;
import museumexhibition.service.impl.MuseumServiceImpl;
import museumexhibition.ui.table.model.ExhibitionTableModel;
import museumexhibition.validation.*;

/**
 *
 * @author Marko Milošević, pravnik
 */
public class ExhibitionNewMultiplyForm extends javax.swing.JDialog {

    private final MuseumService museumService;
    private final ExhibitService exhibitService;
    private final ExhibitionService exhibitionService;

    /**
     * Creates new form ExhibitionNewMultiplyForm
     */
    public ExhibitionNewMultiplyForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        museumService = new MuseumServiceImpl();
        exhibitService = new ExhibitServiceImpl();
        exhibitionService = new ExhibitionServiceImpl();
        prepareForm();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlCombo = new javax.swing.JPanel();
        lblExhibit = new javax.swing.JLabel();
        comboExhibit = new javax.swing.JComboBox<>();
        lblMuseum = new javax.swing.JLabel();
        comboMuseum = new javax.swing.JComboBox<>();
        btnChange = new javax.swing.JButton();
        pnlName = new museumexhibition.ui.components.MyInputComponent();
        pnlDate = new museumexhibition.ui.components.MyInputComponent();
        pnlDays = new museumexhibition.ui.components.MyInputComponent();
        btnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblExhibition = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New exhibitions");

        lblExhibit.setText("Exhibit:");

        comboExhibit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblMuseum.setText("Museum:");

        comboMuseum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMuseum.setEnabled(false);

        btnChange.setText("Change museum");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlComboLayout = new javax.swing.GroupLayout(pnlCombo);
        pnlCombo.setLayout(pnlComboLayout);
        pnlComboLayout.setHorizontalGroup(
            pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComboLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExhibit)
                    .addComponent(lblMuseum))
                .addGap(71, 71, 71)
                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboMuseum, 0, 326, Short.MAX_VALUE)
                    .addComponent(comboExhibit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChange)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlComboLayout.setVerticalGroup(
            pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComboLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExhibit)
                    .addComponent(comboExhibit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMuseum)
                    .addComponent(comboMuseum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange))
                .addContainerGap())
        );

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblExhibition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblExhibition);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnAdd))
                            .addComponent(pnlDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Exhibit exhibit = (Exhibit) comboExhibit.getSelectedItem();
        Museum museum = (Museum) comboMuseum.getSelectedItem();
        try {
            String name = pnlName.getValue();
            String jdate = pnlDate.getValue();
            Date date = new SimpleDateFormat("dd.MM.yyyy.").parse(jdate);
            int durationInDays = Integer.parseInt(pnlDays.getValue());
            Exhibition exhibition = new Exhibition(museum, exhibit, date, name, durationInDays);
            int option = JOptionPane.showConfirmDialog(null, "Are you sure?", "Add object?", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                ExhibitionTableModel etm = (ExhibitionTableModel) tblExhibition.getModel();
                etm.addRow(exhibition);
                comboMuseum.setEnabled(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please update values!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        ExhibitionTableModel etm = (ExhibitionTableModel) tblExhibition.getModel();
        List<Exhibition> exhibitions = etm.getData();
        try {
            int option = JOptionPane.showConfirmDialog(null, "Are you sure?", "Save list?", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                exhibitionService.save(exhibitions);
                JOptionPane.showMessageDialog(this, "List is saved!");
                dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error:" + ex.getMessage());
            dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure?", "Change museum?", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            comboMuseum.setEnabled(true);
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> comboExhibit;
    private javax.swing.JComboBox<Object> comboMuseum;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblExhibit;
    private javax.swing.JLabel lblMuseum;
    private javax.swing.JPanel pnlCombo;
    private museumexhibition.ui.components.MyInputComponent pnlDate;
    private museumexhibition.ui.components.MyInputComponent pnlDays;
    private museumexhibition.ui.components.MyInputComponent pnlName;
    private javax.swing.JTable tblExhibition;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        pnlName.init("*Name:", "", "");
        pnlName.setValidator(new RequiredTextValidator());
        pnlDate.init("*Opening date:", "", "");
        pnlDate.setValidator(new RequiredDateValidator());
        pnlDays.init("*Duration in days:", "", "");
        pnlDays.setValidator(new RequiredDurationInDaysValidator());

        comboExhibit.removeAllItems();
        try {
            List<Exhibit> exhibits = exhibitService.getAll();
            for (Exhibit exhibit : exhibits) {
                comboExhibit.addItem(exhibit);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        comboMuseum.removeAllItems();
        try {
            List<Museum> museums = museumService.getAll();
            for (Museum museum : museums) {
                comboMuseum.addItem(museum);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        TableModel tm = new ExhibitionTableModel(new ArrayList<>());
        tblExhibition.setModel(tm);
    }
}
