package museumexhibition.ui.form.exhibition;

import java.util.List;
import museumexhibition.domain.*;
import museumexhibition.service.ExhibitService;
import museumexhibition.service.ExhibitionService;
import museumexhibition.service.impl.ExhibitServiceImpl;
import museumexhibition.service.impl.ExhibitionServiceImpl;

/**
 *
 * @author Marko Milošević, pravnik
 */
public class ExhibitionAddExhibit extends javax.swing.JDialog {

    private ExhibitService exhibitService;
    private ExhibitionService exhibitionService;
    private Exhibition exhibition;

    /**
     * Creates new form ExhibitionAddExhibit
     */
    public ExhibitionAddExhibit(java.awt.Frame parent, boolean modal, Exhibition exhibition) {
        super(parent, modal);
        initComponents();
        this.exhibition = exhibition;
        exhibitService = new ExhibitServiceImpl();
        exhibitionService = new ExhibitionServiceImpl();
        fillCombo();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblExhibit = new javax.swing.JLabel();
        comboExhibit = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add exhibit ");

        lblExhibit.setText("Exhibit:");

        comboExhibit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblExhibit)
                        .addGap(71, 71, 71)
                        .addComponent(comboExhibit, 0, 236, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExhibit)
                    .addComponent(comboExhibit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnAdd))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Exhibition showing = new Exhibition();
        showing.setMuseum(exhibition.getMuseum());
        showing.setDurationInDays(exhibition.getDurationInDays());
        showing.setName(exhibition.getName());
        showing.setOpening(exhibition.getOpening());
        Exhibit exhibit = (Exhibit) comboExhibit.getSelectedItem();
        showing.setExhibit(exhibit);
        try {
            exhibitionService.save(showing);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<Object> comboExhibit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExhibit;
    // End of variables declaration//GEN-END:variables

    private void fillCombo() {
        comboExhibit.removeAllItems();
        try {
            List<Exhibit> exhibits = exhibitService.getAll();
            for (Exhibit exhibit : exhibits) {
                comboExhibit.addItem(exhibit);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
